name: adventure_works
version: '1.0'
config-version: 2

profile: adventure_works

models:
  adventure_works_dbt:

    +catalog: adventure_works

    staging:
      +schema: staging
      +materialized: view

    intermediate:
      +schema: intermediate
      +materialized: view

    marts:
      +schema: marts
      +materialized: table

      dimensions:
        +materialized: table

      facts:
        +materialized: table

vars:
  gross_sales_2011_expected: 12646112.16
    